(define first car)
(define rest cdr)
(define stack '())
(define stackTemp '())
(define tempArea '())

(define (read-keyboard-as-string) ; this function returns keyboard input as a string
            (let ((char (read-char)))
              (if (char=? char #\newline)
                  '()
                  (list->string
                   (let loop ((char char))
                     (if (char=? char #\newline)
                         '()
                         (cons char (loop (read-char)))
                     )
                   )
                  )
              )
            )
)

(define (push_back element) 
  (set! stack (append (list element) stack) 
       )
  )

(define (DROP) (begin 
                 (define temp '() )
                 (set! stack 
                       (append temp (cdr stack) ) 
                       )
                 )
  )

(define (POP)
  (set! tempArea (first stack))
  (set! stack (rest stack))
  tempArea
  )

(define (SAVE)
  (push_back tempArea)
  )

(define (DUP)
  (push_back (first stack))
  )

(define (SWAP)
  (define x (first stack))
  (pop)
  (pop)
  (push_back x)
  (SAVE)
  )

(define (CLEAR)
  (set! stack '())
  )

(define (STACK x)
  (cond ((not (empty? x))
     (display (first x))
     (display #\newline)
     (STACK (rest x)))
  ))

(define (main)
  (display "UofL> ")
  (let
   ((input-list (regexp-split #px" " (read-keyboard-as-string))))
    (parse-input input-list)
    (main)
  )
)

(define parse-input (lambda (input)
  (cond
    ((string->number (first input)) (push_back (string->number (first input))))
    ((string=? "+" (first input)) (push_back (+ (POP) (POP))))
    ((string=? "-" (first input)) (push_back (- (POP) (POP))))
    ((string=? "/" (first input)) (push_back (/ (POP) (POP))))
    ((string=? "*" (first input)) (push_back (* (POP) (POP))))
    ((string=? ">" (first input)) (push_back (> (POP) (POP))))
    ((string=? "<" (first input)) (push_back (< (POP) (POP))))
    ((string=? ">=" (first input)) (push_back (>= (POP) (POP))))
    ((string=? "<=" (first input)) (push_back (<= (POP) (POP))))
    ((string-ci=? "swap" (first input)) (SWAP))
    ((string-ci=? "dup" (first input)) (DUP))
    ((string-ci=? "pop" (first input)) (POP))
    ((string-ci=? "save" (first input)) (SAVE))
    ((string-ci=? "drop" (first input)) (DROP))
    ((string-ci=? "clear" (first input)) (CLEAR))
    ((string-ci=? "stack" (first input)) (STACK stack))
    ((string-ci=? "." (first input)) 
     ( let ()
      (if (> (length input) 1)
         (display (string->stringList input))
          (display (first stack)))
      (display #\newline)))
    )
   (when (> (length (rest input)) 0)
       (parse-input (rest input))
       
     )
  ))

(define (string->stringList input)
  (apply string-append ( rest ( apply append (map (lambda (x) (list " " x)) (rest input)))))
)