#lang scheme
(define first car)
(define rest cdr)
(define stack '())
(define stackTemp '())
(define tempArea '())

(define (read-keyboard-as-string) ; this function returns keyboard input as a string
            (let ((char (read-char)))
              (if (char=? char #\newline)
                  '()
                  (list->string
                   (let loop ((char char))
                     (if (char=? char #\newline)
                         '()
                         (cons char (loop (read-char)))
                     )
                   )
                  )
              )
            )
)

(define (push_back element) 
  (set! stack (append (list element) stack) 
       )
  )

(define (DROP) (begin 
                 (define temp '() )
                 (set! stack 
                       (append temp (cdr stack) ) 
                       )
                 )
  )
(define drop DROP)

(define (POP)
  (set! tempArea (first stack))
  (define x (first stack))
  (set! stack (rest stack))
  tempArea
  )
(define pop POP)

(define (SAVE)
  (push_back tempArea)
  )
(define save SAVE)

(define (DUP)
  (push_back (first stack))
  )
(define dup DUP)

(define (SWAP)
  (define x (first stack))
  (pop)
  (pop)
  (push_back x)
  (save)
  )
(define swap SWAP)

(define (main)
  (printf "UofL> ")
  (define raw-input (read-keyboard-as-string))
   (define input-list (string-split raw-input))
   (parse-input input-list)
   (main)
  )

(define parse-input (lambda (input)
  (cond
    ((string->number (first input)) (push_back (string->number (first input))))
    ((string=? "+" (first input)) (push_back (+ (pop) (pop))))
    ((string=? "-" (first input)) (push_back (- (pop) (pop))))
    ((string=? "/" (first input)) (push_back (/ (pop) (pop))))
    ((string=? "*" (first input)) (push_back (* (pop) (pop))))
    ((string=? ">" (first input)) (push_back (> (pop) (pop))))
    ((string=? "<" (first input)) (push_back (< (pop) (pop))))
    ((string=? ">=" (first input)) (push_back (>= (pop) (pop))))
    ((string=? "<=" (first input)) (push_back (<= (pop) (pop))))
    ((string=? "swap" (first input)) (swap))
    ((string=? "dup" (first input)) (dup))
    ((string=? "pop" (first input)) (pop))
    ((string=? "save" (first input)) (swap))
    ((string=? "drop" (first input)) (drop))
    ((string=? "." (first input)) 
     (if (> (length input) 1)
         (push_back(string-join (rest input) " "))
         (displayln (first stack))))
    )
   (when (> (length (rest input)) 0)
       (parse-input (rest input))
       
     )
  ))